import { $, component$, useOnWindow, useSignal, useStyles$ } from "@builder.io/qwik";
import { routeLoader$, type DocumentHead } from "@builder.io/qwik-city";
import type { RequestHandler } from "@builder.io/qwik-city";
import styles from './styles.css?inline';
import InfiniteList from '~/components/infinite-list/inifinite-list';
import { DefaultApi } from "~/typescript-axios/api";
import { Configuration } from "~/typescript-axios";

export const onGet: RequestHandler = async ({ cacheControl }) => {
  // Control caching for this request for best performance and to reduce hosting costs:
  // https://qwik.builder.io/docs/caching/
  cacheControl({
    // Always serve a cached response by default, up to a week stale
    staleWhileRevalidate: 60 * 60 * 24 * 7,
    // Max once every 5 seconds, revalidate on the server to get a fresh version of this page
    maxAge: 5,
  });
};

export const usePageLoad = routeLoader$(async () => {
  const api = new DefaultApi(new Configuration({
    basePath: 'http://localhost:3000',
  }))
  const {data} = await api.exampleApi()
  return data
});

function useInLoad() {
  const onload = useSignal(false);
  useOnWindow(
    'load',
    $(() => {
      onload.value = true;
    })
  );
  return onload.value;
}

export default component$(() => {
  useStyles$(styles);
  const onload = useInLoad()
  const PER_PAGE = 100
  const loadMore = useSignal(true);
	const itemsSig = useSignal([...new Array(PER_PAGE).keys()]);
  const pageData = usePageLoad(); 

  return (
    <main 
      style={{height: '100vh'}}
    >
      <div style={{display: 'flex', background: 'grey', width: '100vw', height: '100vh', contain: 'strict'}}>
        <div style={{margin: 'auto', width: 'fit-content'}}>First View</div>
      </div>
      {onload && 
      <InfiniteList
				loadMore={loadMore.value}
				onLoadMore$={$(async () => {
					itemsSig.value = [...itemsSig.value, ...new Array(PER_PAGE).keys()];
					loadMore.value = itemsSig.value.length < 1000;
				})}
			>
				{itemsSig.value.map((_, key) => (
					<div 
            key={key} 
            style={{
              contentVisibility: 'auto',
              containIntrinsicSize: '0 30px',
            }}
          >
            {pageData.value.message}{key}
          </div>
				))}
				<div q:slot='loading' >
          Loading...
				</div>
			</InfiniteList>}
    </main>
  );
});


export const head: DocumentHead = {
  title: "Create Qwik App",
  meta: [
    {
      name: "description",
      content: "Generated by create next app",
    },
  ],
};
