version: "3.1"

services:
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - mongo_network
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    networks:
      - mongo_network
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo


volumes:
  mongodb_data:

networks:
  mongo_network: