/* tslint:disable */
/* eslint-disable */
/**
 * API
 * The API Reference
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AppResponseDto
 */
export interface AppResponseDto {
    /**
     * メッセージ
     * @type {string}
     * @memberof AppResponseDto
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * この Object の種別。ここでは必ず error が入ります。
     * @type {string}
     * @memberof ModelError
     */
    'object': string;
    /**
     * エラーコード文字列
     * @type {string}
     * @memberof ModelError
     */
    'code': string;
    /**
     * エラーメッセージ
     * @type {string}
     * @memberof ModelError
     */
    'message': string;
    /**
     * エラー詳細 Object の配列
     * @type {Array<string>}
     * @memberof ModelError
     */
    'details': Array<string>;
}
/**
 * 
 * @export
 * @interface UserLoginDto
 */
export interface UserLoginDto {
    /**
     * email
     * @type {string}
     * @memberof UserLoginDto
     */
    'email': string;
    /**
     * password
     * @type {string}
     * @memberof UserLoginDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {
    /**
     * name
     * @type {string}
     * @memberof UserResponseDto
     */
    'name': string;
    /**
     * token
     * @type {string}
     * @memberof UserResponseDto
     */
    'token': string;
}
/**
 * 
 * @export
 * @interface UserSignupDto
 */
export interface UserSignupDto {
    /**
     * name
     * @type {string}
     * @memberof UserSignupDto
     */
    'name': string;
    /**
     * email
     * @type {string}
     * @memberof UserSignupDto
     */
    'email': string;
    /**
     * password
     * @type {string}
     * @memberof UserSignupDto
     */
    'password': string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * response test message
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exampleApi: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * load user
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loadUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * login user
         * @summary 
         * @param {UserLoginDto} userLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (userLoginDto: UserLoginDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userLoginDto' is not null or undefined
            assertParamExists('login', 'userLoginDto', userLoginDto)
            const localVarPath = `/api/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userLoginDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * signup user
         * @summary 
         * @param {UserSignupDto} userSignupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup: async (userSignupDto: UserSignupDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userSignupDto' is not null or undefined
            assertParamExists('signup', 'userSignupDto', userSignupDto)
            const localVarPath = `/api/users/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userSignupDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * response test message
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exampleApi(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exampleApi(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.exampleApi']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * load user
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async loadUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.loadUser(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.loadUser']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * login user
         * @summary 
         * @param {UserLoginDto} userLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(userLoginDto: UserLoginDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(userLoginDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.login']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * signup user
         * @summary 
         * @param {UserSignupDto} userSignupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signup(userSignupDto: UserSignupDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signup(userSignupDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['DefaultApi.signup']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * response test message
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exampleApi(options?: any): AxiosPromise<AppResponseDto> {
            return localVarFp.exampleApi(options).then((request) => request(axios, basePath));
        },
        /**
         * load user
         * @summary 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        loadUser(options?: any): AxiosPromise<UserResponseDto> {
            return localVarFp.loadUser(options).then((request) => request(axios, basePath));
        },
        /**
         * login user
         * @summary 
         * @param {UserLoginDto} userLoginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(userLoginDto: UserLoginDto, options?: any): AxiosPromise<UserResponseDto> {
            return localVarFp.login(userLoginDto, options).then((request) => request(axios, basePath));
        },
        /**
         * signup user
         * @summary 
         * @param {UserSignupDto} userSignupDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup(userSignupDto: UserSignupDto, options?: any): AxiosPromise<UserResponseDto> {
            return localVarFp.signup(userSignupDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * response test message
     * @summary 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public exampleApi(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).exampleApi(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * load user
     * @summary 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public loadUser(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).loadUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * login user
     * @summary 
     * @param {UserLoginDto} userLoginDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public login(userLoginDto: UserLoginDto, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).login(userLoginDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * signup user
     * @summary 
     * @param {UserSignupDto} userSignupDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public signup(userSignupDto: UserSignupDto, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).signup(userSignupDto, options).then((request) => request(this.axios, this.basePath));
    }
}



